### ISSUE TITLE
Installed package uses deprecated `np.Inf` causing NumPy 2.0 errors

### ISSUE THREAD

**Issue by mrbakhtyari** [mzelling/repliclust#10]
I encountered an issue when using the installed version of this package, where the following error is raised:

> AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.

After forking the repository and reviewing the source code, I can confirm that the repository already uses the correct `np.inf` (with lowercase "inf"). However, the package still seems to use the outdated `np.Inf`, which is not valid in NumPy 2.0 and causes this error.

1. Install the package via `pip install repliclust`.
2. Run any code that interacts with `np.inf`.
3. The error will occur, indicating the use of `np.Inf` instead of `np.inf`.

The package should use `np.inf` to avoid errors when working with NumPy 2.0 and later. The installed package uses `np.Inf`, which was deprecated and removed in NumPy 2.0, resulting in a runtime error. Please release a new version of the package that reflects the correct usage of `np.inf`, as already fixed in the source code within the repository.

Thank you!

**Comment by mzelling** [comment]
Thanks for opening this issue. I have bumped the version to 1.0.0. and uploaded it to PyPI. Running pip install should now get you the new version. Let me know if this fixes the problem.

**Comment by mrbakhtyari** [comment]
Yes, It works fine. 

Many thanks.
