### ISSUE TITLE
Installation Error in Version 0.0.4: Missing 'distutils ' and 'pkgutil' Issue

### ISSUE THREAD

**Issue by mrbakhtyari** [mzelling/repliclust#9]
I am experiencing issues when attempting to install version 0.0.4 of the package. The installation process fails with two specific errors:

1. ModuleNotFoundError: No module named 'distutils'
2. AttributeError: module 'pkgutil' has no attribute 'ImpImporter'

This issue does not occur with version 0.0.3, which installs and functions correctly. The errors suggest there may be compatibility or dependency issues introduced in version 0.0.4.

Installing and upgrading 'pip', 'wheel', and 'setuptools' resolved the 'distutils' error. The upgrade and installation command is:

`pip install --upgrade pip setuptools wheel`

Environment
- Python version: 3.12
- Pip version: 24.2
- Operating System: Windows

Thank you for looking into this issue. Please let me know if further information is required.

**Comment by mzelling** [comment]
@mrbakhtyari Thank you for opening this issue. Could you check if you are still encountering the error with version 0.0.5 of repliclust?

**Comment by mrbakhtyari** [comment]
Thank you for fixing the issue. The installation now works perfectly.
